# Lab 3: Pytorch Fundamentals

# objective
1. To understand the fundamentals of PyTorch and its tensor-based architecture for machine learning and deep learning applications.

2. To learn how to create, manipulate, and analyze different types of tensors, including scalars, vectors, matrices, and higher-dimensional tensors.

3. To perform various tensor operations such as arithmetic operations, matrix multiplication, reshaping, indexing, and aggregation.

4. To explore data conversion between NumPy arrays and PyTorch tensors, and understand the use of CPU and GPU devices for computation.


# Theory

#Introduction to PyTorch

PyTorch is an open-source machine learning and deep learning framework developed by Meta (Facebook). It provides a flexible platform for building, training, and deploying neural networks. PyTorch uses tensors as its primary data structure and supports automatic differentiation, making it widely used for research and industrial AI applications.

#Tensor

A tensor is the fundamental data structure in PyTorch. It is a multi-dimensional array used to store numerical data. Tensors are similar to NumPy arrays but can utilize GPUs for faster computation.

#Types of Tensors
1. Scalar

A scalar is a tensor containing a single value and has zero dimensions.

Example: tensor(7)

2. Vector

A vector is a one-dimensional tensor containing multiple values.

Example: [7, 8, 9, 10]

3. Matrix

A matrix is a two-dimensional tensor arranged in rows and columns.

Example:

[[1,2,3],
 [4,5,6],
 [7,8,9]]

4. Higher-Dimensional Tensor

A tensor with three or more dimensions is used to represent complex data such as images, videos, and datasets.

#Tensor Creation

PyTorch provides various methods for creating tensors:

torch.tensor() – Creates a tensor from data.

torch.rand() – Creates a tensor with random values.

torch.zeros() – Creates a tensor filled with zeros.

torch.ones() – Creates a tensor filled with ones.

torch.arange() – Creates a tensor with a sequence of values.

Tensor Attributes

#Important tensor properties include:

#Shape

Represents the dimensions of a tensor.

#Datatype (dtype)

Specifies the type of data stored in the tensor, such as:

float32

float16

float64

int32

int64

Device

Indicates where the tensor is stored:

CPU

GPU

#Tensor Operations


Tensor operations are essential in machine learning and deep learning.

Arithmetic Operations

Addition

Subtraction

Multiplication

Division

Element-wise Multiplication

Each element of one tensor is multiplied by the corresponding element of another tensor.

#Matrix Multiplication

Matrix multiplication combines two matrices following linear algebra rules. For multiplication to be valid, the inner dimensions must match.

Example:

(2 × 3) × (3 × 2) = (2 × 2)

#Tensor Aggregation Operations

Aggregation operations summarize tensor values.

#Common Functions
min() – Returns the minimum value.

max() – Returns the maximum value.

mean() – Returns the average value.

sum() – Returns the sum of all elements.

argmin() – Returns the index of the minimum value.

argmax() – Returns the index of the maximum value.

Tensor Reshaping

Reshaping changes the dimensions of a tensor without altering its data.

reshape()

Changes the tensor shape while maintaining the same elements.

view()

Returns a new view of the tensor sharing the same memory.

stack()

Combines multiple tensors along a new dimension.

Squeeze and Unsqueeze Operations

squeeze()

Removes dimensions of size 1 from a tensor.

unsqueeze()

Adds a new dimension of size 1 at a specified position.

These operations help maintain compatible tensor shapes during neural network computations.

#Permutation of Dimensions

torch.permute() rearranges the order of tensor dimensions without changing the data itself. It is commonly used when working with image data where dimensions need to be reordered.

#Tensor Indexing

Indexing allows access to specific tensor elements, rows, columns, or slices.

Examples include:

Accessing individual elements

Selecting rows and columns

Slicing tensors using : operator

#Conversion Between NumPy and PyTorch

PyTorch and NumPy can easily exchange data.

#NumPy to Tensor
torch.from_numpy()
#Tensor to NumPy
tensor.numpy()

This interoperability is useful for scientific computing and data preprocessing.

GPU Support in PyTorch

PyTorch supports GPU acceleration using CUDA. Computations performed on GPUs are significantly faster than CPUs for large-scale deep learning tasks.

#Common functions:

torch.cuda.is_available()

torch.cuda.device_count()

tensor.to('cuda')

If no GPU is available, PyTorch automatically uses the CPU.

In [103]:
import torch
torch.__version__

'2.12.0+cu126'

In [53]:
# creating scalar using tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [54]:
print(scalar.ndim)
print(scalar.item()) #only works with one-element tensors
print(scalar.shape)

0
7
torch.Size([])


In [55]:
# vector
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [56]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


In [57]:
# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


In [59]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [60]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [61]:
# randomize tensors
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.2682, 0.1750, 0.3024],
         [0.9990, 0.2360, 0.1996]]),
 torch.float32)

In [62]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [63]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [64]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [65]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([2.0, 4.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [68]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [69]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0589, 0.7950, 0.1990, 0.2162],
        [0.3057, 0.5424, 0.8248, 0.9858],
        [0.8512, 0.7924, 0.3302, 0.7316]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [70]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [71]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [72]:
tensor

tensor([1, 2, 3])

In [73]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [74]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([-90, -80, -70])

In [75]:
tensor

tensor([-9, -8, -7])

In [76]:
tensor = tensor + 10
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)
print("Equals:", torch.multiply(tensor, tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [77]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
print(tensor * tensor)

# Matrix multiplication
print(torch.matmul(tensor, tensor))

tensor([1, 4, 9])
tensor(14)


In [78]:
# # Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [79]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [80]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [81]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [82]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

torch.float32


tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [83]:
# Create a tensor
import torch
x = torch.arange(1., 9.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 8) # try other shapes, it will produce an error.
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [84]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [85]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 8)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [86]:
z = x.view(2,4)
z, z.shape


(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [87]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [88]:
x = torch.arange(6)

a = x.view(2, 3)
b = x.reshape(2, 3)

a[0, 0] = 100
print(x)

tensor([100,   1,   2,   3,   4,   5])


In [89]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5],
        [100,   1,   2,   3,   4,   5]])

In [90]:
# Stacking using dim=1
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[100, 100, 100, 100],
        [  1,   1,   1,   1],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3],
        [  4,   4,   4,   4],
        [  5,   5,   5,   5]])

In [91]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [92]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(x.shape)

y = x.permute(1, 0)

print(y)
print(y.shape)

torch.Size([2, 3])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])


In [93]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [94]:
print(x[:, 0]) # Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, :, 1])# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, 1, 1]) # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[0, 0, :]) # same as x[0][0]

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


In [95]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [97]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [98]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [99]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [100]:
# Count number of devices
torch.cuda.device_count()

0

In [101]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [102]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Discussion

In this lab, the fundamental concepts of PyTorch were explored through practical implementation. Different types of tensors, including scalars, vectors, matrices, and higher-dimensional tensors, were created and manipulated. Various tensor operations such as arithmetic operations, matrix multiplication, reshaping, stacking, indexing, and datatype conversion were performed. The lab also demonstrated the interoperability between NumPy arrays and PyTorch tensors, as well as the process of checking and utilizing GPU support. Through these exercis|es, a clear understanding of tensor operations and data handling in PyTorch was developed, which forms the basis of deep learning applications.

# Conclusion

This lab successfully introduced the core features of PyTorch and tensor manipulation techniques. we gained hands-on experience in creating and operating on tensors, understanding tensor properties, performing mathematical computations, reshaping data, and managing devices for computation. The knowledge acquired in this lab provides a strong foundation for implementing machine learning and deep learning models using PyTorch in future experiments and projects.

Overall, this lab helped develop a strong foundation in PyTorch programming and tensor operations. The knowledge and skills gained from this experiment are essential for implementing neural networks, training deep learning models, and solving real-world artificial intelligence problems. These concepts will serve as the building blocks for more advanced topics in machine learning and deep learning.